/* This file will create the unicode_point TABLE which will be used IN the */
/* CHARACTER cleaning functions. the TABLE IS a mapping FROM a unicode */
/* CHARACTER TO the simplified character(s) that replace it IN a company name */ 
/* (although it can be etended TO other strings AS well.) */

/* transliteration OF codepoints is hard. */
/* See https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block) */
/* https://en.wikipedia.org/wiki/Latin-1_Supplement_%28Unicode_block%29 */

/* These functions ARE grouped BY the codepoints that they operate upon.
 * Unless otherwise defined, I'll be using the transliteration rules from
* unidecode: */
/* https://metacpan.org/source/SBURKE/Text-Unidecode-1.30/lib/Text/Unidecode/x00.pm */

CREATE TABLE etl.unicode_point (
  unicode_character TEXT PRIMARY KEY,
  codepoint TEXT UNIQUE NOT NULL,
  romanized_character TEXT NOT NULL,
  simple_romanized_character TEXT NOT NULL,
  description TEXT,
  block_name TEXT,
  category TEXT,
  notes TEXT,
  is_simplified BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_unicode_point_cover_simple ON etl.unicode_point (
  unicode_character, is_simplified, simple_romanized_character
  );
CREATE INDEX ix_unicode_point_codepoint ON etl.unicode_point (codepoint);
CREATE INDEX ix_unicode_point_block_name ON etl.unicode_point (block_name);

INSERT INTO etl.unicode_point (
  codepoint,
  unicode_character,
  romanized_character,
  simple_romanized_character,
  description,
  block_name,
  category,
  notes,
  is_simplified
) VALUES
--Standard set of characters that are consistent and exist for Basic Latin set
('0000', 'NUL', '', '', 'Null character', 'Basic Latin', 'Control', 'NUL', FALSE),
('0001', 'SOH', '', '', 'Start of Heading', 'Basic Latin', 'Control', 'SOH', FALSE),
('0002', 'STX', '', '', 'Start of Text', 'Basic Latin', 'Control', 'STX', FALSE),
('0003', 'ETX', '', '', 'End-of-text character', 'Basic Latin', 'Control', 'ETX', FALSE),
('0004', 'EOT', '', '', 'End-of-transmission character', 'Basic Latin', 'Control', 'EOT', FALSE),
('0005', 'ENQ', '', '', 'Enquiry character', 'Basic Latin', 'Control', 'ENQ', FALSE),
('0006', 'ACK', '', '', 'Acknowledge character', 'Basic Latin', 'Control', 'ACK', FALSE),
('0007', 'BEL', '', '', 'Bell character', 'Basic Latin', 'Control', 'BEL', FALSE),
('0008', 'BS', '', '', 'Backspace', 'Basic Latin', 'Control', 'BS', FALSE),
('0009', '	', ' ', ' ', 'Horizontal tab', 'Basic Latin', 'Whitespace', 'HT', FALSE),
('000A', 'LF', '', '', 'Line feed', 'Basic Latin', 'Control', 'LF', FALSE),
('000B', 'VT', '', '', 'Vertical tab', 'Basic Latin', 'Control', 'VT', FALSE),
('000C', 'FF', '', '', 'Form feed', 'Basic Latin', 'Control', 'FF', FALSE),
('000D', 'CR', '', '', 'Carriage return', 'Basic Latin', 'Control', 'CR', FALSE),
('000E', 'SO', '', '', 'Shift Out', 'Basic Latin', 'Control', 'SO', FALSE),
('000F', 'SI', '', '', 'Shift In', 'Basic Latin', 'Control', 'SI', FALSE),
('0010', 'DLE', '', '', 'Data Link Escape', 'Basic Latin', 'Control', 'DLE', FALSE),
('0011', 'DC1', '', '', 'Device Control 1', 'Basic Latin', 'Control', 'DC1', FALSE),
('0012', 'DC2', '', '', 'Device Control 2', 'Basic Latin', 'Control', 'DC2', FALSE),
('0013', 'DC3', '', '', 'Device Control 3', 'Basic Latin', 'Control', 'DC3', FALSE),
('0014', 'DC4', '', '', 'Device Control 4', 'Basic Latin', 'Control', 'DC4', FALSE),
('0015', 'NAK', '', '', 'Negative-acknowledge character', 'Basic Latin', 'Control', 'NAK', FALSE),
('0016', 'SYN', '', '', 'Synchronous Idle', 'Basic Latin', 'Control', 'SYN', FALSE),
('0017', 'ETB', '', '', 'End of Transmission Block', 'Basic Latin', 'Control', 'ETB', FALSE),
('0018', 'CAN', '', '', 'Cancel character', 'Basic Latin', 'Control', 'CAN', FALSE),
('0019', 'EM', '', '', 'End of Medium', 'Basic Latin', 'Control', 'EM', FALSE),
('001A', 'SUB', '', '', 'Substitute character', 'Basic Latin', 'Control', 'SUB', FALSE),
('001B', 'ESC', '', '', 'Escape character', 'Basic Latin', 'Control', 'ESC', FALSE),
('001C', 'FS', '', '', 'File Separator', 'Basic Latin', 'Control', 'FS', FALSE),
('001D', 'GS', '', '', 'Group Separator', 'Basic Latin', 'Control', 'GS', FALSE),
('001E', 'RS', '', '', 'Record Separator', 'Basic Latin', 'Control', 'RS', FALSE),
('001F', 'US', '', '', 'Unit Separator', 'Basic Latin', 'Control', 'US', FALSE),
('0020', ' ', ' ', ' ', 'Space', 'Basic Latin', 'Whitespace', 'SP', TRUE),
('0021', '!', '!', '', 'Exclamation mark', 'Basic Latin', 'Punctuation', 'EXC', FALSE),
('0022', '"', '"', '', 'Quotation mark', 'Basic Latin', 'Punctuation', 'QUO', FALSE),
('0023', '#', '#', '', 'Number sign', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0024', '$', '$', '', 'Dollar sign', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0025', '%', '%', '', 'Percent sign', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0026', '&', '&', '&', 'Ampersand', 'Basic Latin', 'Punctuation', NULL, TRUE),
('0027', '''', '''', '''', 'Apostrophe', 'Basic Latin', 'Punctuation', NULL, TRUE),
('0028', '(', '(', '', 'Left parenthesis', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0029', ')', ')', '', 'Right parenthesis', 'Basic Latin', 'Punctuation', NULL, FALSE),
('002A', '*', '*', '', 'Asterisk', 'Basic Latin', 'Punctuation', NULL, FALSE),
('002B', '+', '+', '', 'Plus sign', 'Basic Latin', 'Punctuation', NULL, FALSE),
('002C', ',', ',', '', 'Comma', 'Basic Latin', 'Punctuation', NULL, FALSE),
('002D', '-', '-', '', 'Hyphen-minus', 'Basic Latin', 'Punctuation', NULL, FALSE),
('002E', '.', '.', '', 'Full stop or period', 'Basic Latin', 'Punctuation', NULL, FALSE),
('002F', '/', '/', '', 'Solidus or Slash', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0030', '0', '0', '0', 'Digit Zero', 'Basic Latin', 'Digit', NULL, TRUE),
('0031', '1', '1', '1', 'Digit One', 'Basic Latin', 'Digit', NULL, TRUE),
('0032', '2', '2', '2', 'Digit Two', 'Basic Latin', 'Digit', NULL, TRUE),
('0033', '3', '3', '3', 'Digit Three', 'Basic Latin', 'Digit', NULL, TRUE),
('0034', '4', '4', '4', 'Digit Four', 'Basic Latin', 'Digit', NULL, TRUE),
('0035', '5', '5', '5', 'Digit Five', 'Basic Latin', 'Digit', NULL, TRUE),
('0036', '6', '6', '6', 'Digit Six', 'Basic Latin', 'Digit', NULL, TRUE),
('0037', '7', '7', '7', 'Digit Seven', 'Basic Latin', 'Digit', NULL, TRUE),
('0038', '8', '8', '8', 'Digit Eight', 'Basic Latin', 'Digit', NULL, TRUE),
('0039', '9', '9', '9', 'Digit Nine', 'Basic Latin', 'Digit', NULL, TRUE),
('003A', ':', ':', '', 'Colon', 'Basic Latin', 'Punctuation', NULL, FALSE),
('003B', ';', ';', '', 'Semicolon', 'Basic Latin', 'Punctuation', NULL, FALSE),
('003C', '<', '<', '', 'Less-than sign', 'Basic Latin', 'Punctuation', NULL, FALSE),
('003D', '=', '=', '', 'Equal sign', 'Basic Latin', 'Punctuation', NULL, FALSE),
('003E', '>', '>', '', 'Greater-than sign', 'Basic Latin', 'Punctuation', NULL, FALSE),
('003F', '?', '?', '', 'Question mark', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0040', '@', '@', '', 'At sign or Commercial at', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0041', 'A', 'A', 'a', 'Latin Capital letter A', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0042', 'B', 'B', 'b', 'Latin Capital letter B', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0043', 'C', 'C', 'c', 'Latin Capital letter C', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0044', 'D', 'D', 'd', 'Latin Capital letter D', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0045', 'E', 'E', 'e', 'Latin Capital letter E', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0046', 'F', 'F', 'f', 'Latin Capital letter F', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0047', 'G', 'G', 'g', 'Latin Capital letter G', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0048', 'H', 'H', 'h', 'Latin Capital letter H', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0049', 'I', 'I', 'i', 'Latin Capital letter I', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('004A', 'J', 'J', 'j', 'Latin Capital letter J', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('004B', 'K', 'K', 'k', 'Latin Capital letter K', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('004C', 'L', 'L', 'l', 'Latin Capital letter L', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('004D', 'M', 'M', 'm', 'Latin Capital letter M', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('004E', 'N', 'N', 'n', 'Latin Capital letter N', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('004F', 'O', 'O', 'o', 'Latin Capital letter O', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0050', 'P', 'P', 'p', 'Latin Capital letter P', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0051', 'Q', 'Q', 'q', 'Latin Capital letter Q', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0052', 'R', 'R', 'r', 'Latin Capital letter R', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0053', 'S', 'S', 's', 'Latin Capital letter S', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0054', 'T', 'T', 't', 'Latin Capital letter T', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0055', 'U', 'U', 'u', 'Latin Capital letter U', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0056', 'V', 'V', 'v', 'Latin Capital letter V', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0057', 'W', 'W', 'w', 'Latin Capital letter W', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0058', 'X', 'X', 'x', 'Latin Capital letter X', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0059', 'Y', 'Y', 'y', 'Latin Capital letter Y', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('005A', 'Z', 'Z', 'z', 'Latin Capital letter Z', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('005B', '[', '[', '', 'Left Square Bracket', 'Basic Latin', 'Punctuation', NULL, FALSE),
('005C', '\', '\', '', 'Backslash [A]', 'Basic Latin', 'Punctuation', NULL, FALSE),
('005D', ']', ']', '', 'Right Square Bracket', 'Basic Latin', 'Punctuation', NULL, FALSE),
('005E', '^', '^', '', 'Circumflex accent', 'Basic Latin', 'Punctuation', NULL, FALSE),
('005F', '_', '_', '', 'Low line', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0060', '`', '`', '', 'Grave accent', 'Basic Latin', 'Punctuation', NULL, FALSE),
('0061', 'a', 'a', 'a', 'Latin Small Letter A', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0062', 'b', 'b', 'b', 'Latin Small Letter B', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0063', 'c', 'c', 'c', 'Latin Small Letter C', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0064', 'd', 'd', 'd', 'Latin Small Letter D', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0065', 'e', 'e', 'e', 'Latin Small Letter E', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0066', 'f', 'f', 'f', 'Latin Small Letter F', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0067', 'g', 'g', 'g', 'Latin Small Letter G', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0068', 'h', 'h', 'h', 'Latin Small Letter H', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0069', 'i', 'i', 'i', 'Latin Small Letter I', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('006A', 'j', 'j', 'j', 'Latin Small Letter J', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('006B', 'k', 'k', 'k', 'Latin Small Letter K', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('006C', 'l', 'l', 'l', 'Latin Small Letter L', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('006D', 'm', 'm', 'm', 'Latin Small Letter M', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('006E', 'n', 'n', 'n', 'Latin Small Letter N', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('006F', 'o', 'o', 'o', 'Latin Small Letter O', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0070', 'p', 'p', 'p', 'Latin Small Letter P', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0071', 'q', 'q', 'q', 'Latin Small Letter Q', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0072', 'r', 'r', 'r', 'Latin Small Letter R', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0073', 's', 's', 's', 'Latin Small Letter S', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0074', 't', 't', 't', 'Latin Small Letter T', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0075', 'u', 'u', 'u', 'Latin Small Letter U', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0076', 'v', 'v', 'v', 'Latin Small Letter V', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0077', 'w', 'w', 'w', 'Latin Small Letter W', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0078', 'x', 'x', 'x', 'Latin Small Letter X', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('0079', 'y', 'y', 'y', 'Latin Small Letter Y', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('007A', 'z', 'z', 'z', 'Latin Small Letter Z', 'Basic Latin', 'ASCII letters', NULL, TRUE),
('007B', '{', '{', '', 'Left Curly Bracket', 'Basic Latin', 'Punctuation', NULL, FALSE),
('007C', '|', '|', '', 'Vertical bar', 'Basic Latin', 'Punctuation', NULL, FALSE),
('007D', '}', '}', '', 'Right Curly Bracket', 'Basic Latin', 'Punctuation', NULL, FALSE),
('007E', '~', '~', '', 'Tilde', 'Basic Latin', 'Punctuation', NULL, FALSE),
('007F', 'DEL', '', '', 'Delete', 'Basic Latin', 'Control', 'DEL', FALSE),
('0080', 'PAD', '', '', 'Padding Character', 'Latin-1 Supplement', 'Control', 'PAD', FALSE),
('0081', 'HOP', '', '', 'High Octet Preset', 'Latin-1 Supplement', 'Control', 'HOP', FALSE),
('0082', 'BPH', '', '', 'Break Permitted Here', 'Latin-1 Supplement', 'Control', 'BPH', FALSE),
('0083', 'NBH', '', '', 'No Break Here', 'Latin-1 Supplement', 'Control', 'NBH', FALSE),
('0084', 'IND', '', '', 'Index', 'Latin-1 Supplement', 'Control', 'IND', FALSE),
('0085', 'NEL', '', '', 'Next Line', 'Latin-1 Supplement', 'Control', 'NEL', FALSE),
('0086', 'SSA', '', '', 'Start of Selected Area', 'Latin-1 Supplement', 'Control', 'SSA', FALSE),
('0087', 'ESA', '', '', 'End of Selected Area', 'Latin-1 Supplement', 'Control', 'ESA', FALSE),
('0088', 'HTS', '', '', 'Character (Horizontal) Tabulation Set', 'Latin-1 Supplement', 'Control', 'HTS', FALSE),
('0089', 'HTJ', '', '', 'Character (Horizontal) Tabulation with Justification', 'Latin-1 Supplement', 'Control', 'HTJ', FALSE),
('008A', 'LTS', '', '', 'Line (Vertical) Tabulation Set', 'Latin-1 Supplement', 'Control', 'LTS', FALSE),
('008B', 'PLD', '', '', 'Partial Line Forward (Down)', 'Latin-1 Supplement', 'Control', 'PLD', FALSE),
('008C', 'PLU', '', '', 'Partial Line Backward (Up)', 'Latin-1 Supplement', 'Control', 'PLU', FALSE),
('008D', 'RI', '', '', 'Reverse Line Feed (Index)', 'Latin-1 Supplement', 'Control', 'RI', FALSE),
('008E', 'SS2', '', '', 'Single-Shift Two', 'Latin-1 Supplement', 'Control', 'SS2', FALSE),
('008F', 'SS3', '', '', 'Single-Shift Three', 'Latin-1 Supplement', 'Control', 'SS3', FALSE),
('0090', 'DCS', '', '', 'Device Control String', 'Latin-1 Supplement', 'Control', 'DCS', FALSE),
('0091', 'PU1', '', '', 'Private Use One', 'Latin-1 Supplement', 'Control', 'PU1', FALSE),
('0092', 'PU2', '', '', 'Private Use Two', 'Latin-1 Supplement', 'Control', 'PU2', FALSE),
('0093', 'STS', '', '', 'Set Transmit State', 'Latin-1 Supplement', 'Control', 'STS', FALSE),
('0094', 'CCH', '', '', 'Cancel character', 'Latin-1 Supplement', 'Control', 'CCH', FALSE),
('0095', 'MW', '', '', 'Message Waiting', 'Latin-1 Supplement', 'Control', 'MW', FALSE),
('0096', 'SPA', '', '', 'Start of Protected Area', 'Latin-1 Supplement', 'Control', 'SPA', FALSE),
('0097', 'EPA', '', '', 'End of Protected Area', 'Latin-1 Supplement', 'Control', 'EPA', FALSE),
('0098', 'SOS', '', '', 'Start of String', 'Latin-1 Supplement', 'Control', 'SOS', FALSE),
('0099', 'SGCI', '', '', 'Single Graphic Character Introducer', 'Latin-1 Supplement', 'Control', 'SGCI', FALSE),
('009A', 'SCI', '', '', 'Single Character Introducer', 'Latin-1 Supplement', 'Control', 'SCI', FALSE),
('009B', 'CSI', '', '', 'Control Sequence Introducer', 'Latin-1 Supplement', 'Control', 'CSI', FALSE),
('009C', 'ST', '', '', 'String Terminator', 'Latin-1 Supplement', 'Control', 'ST', FALSE),
('009D', 'OSC', '', '', 'Operating System Command', 'Latin-1 Supplement', 'Control', 'OSC', FALSE),
('009E', 'PM', '', '', 'Private Message', 'Latin-1 Supplement', 'Control', 'PM', FALSE),
('009F', 'APC', '', '', 'Application Program Command', 'Latin-1 Supplement', 'Control', 'APC', FALSE),
('00A0', ' ', ' ', ' ', 'Non-breaking space', 'Latin-1 Supplement', 'Whitespace', 'NBSP', FALSE),
('00A1', '¡', '!', '', 'Inverted exclamation mark', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00A2', '¢', 'C/', '', 'Cent sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00A3', '£', 'PS', '', 'Pound sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00A4', '¤', '$?', '', 'Currency sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00A5', '¥', 'Y=', '', 'Yen sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00A6', '¦', '|', '', 'Broken bar', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00A7', '§', 'SS', '', 'Section sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00A8', '¨', '"', '', 'Diaeresis', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00A9', '©', '(c)', '', 'Copyright sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00AA', 'ª', 'a', '', 'Feminine Ordinal Indicator', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00AB', '«', '<<', '', 'Left-pointing double angle quotation mark', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00AC', '¬', '!', '', 'Not sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00AD', '­', '', '', 'Soft hyphen', 'Latin-1 Supplement', 'Whitespace', 'SHY', FALSE), --Technically an invisible character, but controls hyphenation across linebreaks.
('00AE', '®', '(r)', '', 'Registered sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00AF', '¯', '-', '', 'Macron', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B0', '°', 'deg', '', 'Degree symbol', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B1', '±', '+-', '', 'Plus-minus sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B2', '²', '2', '', 'Superscript two', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B3', '³', '3', '', 'Superscript three', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B4', '´', '''', '', 'Acute accent', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B5', 'µ', 'u', '', 'Micro sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B6', '¶', 'P', '', 'Pilcrow sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B7', '·', '*', '', 'Middle dot', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B8', '¸', ',', '', 'Cedilla', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00B9', '¹', '1', '', 'Superscript one', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00BA', 'º', 'o', '', 'Masculine ordinal indicator', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00BB', '»', '>>', '', 'Right-pointing double-angle quotation mark', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00BC', '¼', '1/4', '', 'Vulgar fraction one quarter', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00BD', '½', '1/2', '', 'Vulgar fraction one half', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00BE', '¾', '3/4', '', 'Vulgar fraction three quarters', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00BF', '¿', '?', '', 'Inverted question mark', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00C0', 'À', 'A', 'a', 'Latin Capital Letter A with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C1', 'Á', 'A', 'a', 'Latin Capital letter A with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C2', 'Â', 'A', 'a', 'Latin Capital letter A with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C3', 'Ã', 'A', 'a', 'Latin Capital letter A with tilde', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C4', 'Ä', 'A', 'a', 'Latin Capital letter A with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C5', 'Å', 'A', 'a', 'Latin Capital letter A with ring above', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C6', 'Æ', 'AE', 'ae', 'Latin Capital letter AE', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C7', 'Ç', 'C', 'c', 'Latin Capital letter C with cedilla', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C8', 'È', 'E', 'e', 'Latin Capital letter E with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00C9', 'É', 'E', 'e', 'Latin Capital letter E with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00CA', 'Ê', 'E', 'e', 'Latin Capital letter E with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00CB', 'Ë', 'E', 'e', 'Latin Capital letter E with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00CC', 'Ì', 'I', 'i', 'Latin Capital letter I with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00CD', 'Í', 'I', 'i', 'Latin Capital letter I with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00CE', 'Î', 'I', 'i', 'Latin Capital letter I with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00CF', 'Ï', 'I', 'i', 'Latin Capital letter I with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D0', 'Ð', 'D', 'd', 'Latin Capital letter Eth', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D1', 'Ñ', 'N', 'n', 'Latin Capital letter N with tilde', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D2', 'Ò', 'O', 'o', 'Latin Capital letter O with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D3', 'Ó', 'O', 'o', 'Latin Capital letter O with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D4', 'Ô', 'O', 'o', 'Latin Capital letter O with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D5', 'Õ', 'O', 'o', 'Latin Capital letter O with tilde', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D6', 'Ö', 'O', 'o', 'Latin Capital letter O with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D7', '×', 'x', '', 'Multiplication sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00D8', 'Ø', 'O', 'o', 'Latin Capital letter O with stroke', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00D9', 'Ù', 'U', 'u', 'Latin Capital letter U with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00DA', 'Ú', 'U', 'u', 'Latin Capital letter U with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00DB', 'Û', 'U', 'u', 'Latin Capital Letter U with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00DC', 'Ü', 'U', 'u', 'Latin Capital Letter U with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00DD', 'Ý', 'Y', 'y', 'Latin Capital Letter Y with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00DE', 'Þ', 'Th', 'th', 'Latin Capital Letter Thorn', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00DF', 'ß', 'ss', 'ss', 'Latin Small Letter sharp S', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E0', 'à', 'a', 'a', 'Latin Small Letter A with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E1', 'á', 'a', 'a', 'Latin Small Letter A with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E2', 'â', 'a', 'a', 'Latin Small Letter A with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E3', 'ã', 'a', 'a', 'Latin Small Letter A with tilde', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E4', 'ä', 'ae', 'ae', 'Latin Small Letter A with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
--Defined in previous matching algorithm
('00E5', 'å', 'a', 'a', 'Latin Small Letter A with ring above', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E6', 'æ', 'ae', 'ae', 'Latin Small Letter AE', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E7', 'ç', 'c', 'c', 'Latin Small Letter C with cedilla', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E8', 'è', 'e', 'e', 'Latin Small Letter E with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00E9', 'é', 'e', 'e', 'Latin Small Letter E with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00EA', 'ê', 'e', 'e', 'Latin Small Letter E with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00EB', 'ë', 'e', 'e', 'Latin Small Letter E with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00EC', 'ì', 'i', 'i', 'Latin Small Letter I with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00ED', 'í', 'i', 'i', 'Latin Small Letter I with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00EE', 'î', 'i', 'i', 'Latin Small Letter I with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00EF', 'ï', 'i', 'i', 'Latin Small Letter I with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00F0', 'ð', 'd', 'd', 'Latin Small Letter Eth', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00F1', 'ñ', 'n', 'n', 'Latin Small Letter N with tilde', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00F2', 'ò', 'o', 'o', 'Latin Small Letter O with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00F3', 'ó', 'o', 'o', 'Latin Small Letter O with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00F4', 'ô', 'o', 'o', 'Latin Small Letter O with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00F5', 'õ', 'o', 'o', 'Latin Small Letter O with tilde', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00F6', 'ö', 'oe', 'oe', 'Latin Small Letter O with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
--Defined in previous matching algorithm
('00F7', '÷', '/', '', 'Division sign', 'Latin-1 Supplement', 'Punctuation', NULL, FALSE),
('00F8', 'ø', 'o', 'o', 'Latin Small Letter O with stroke', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00F9', 'ù', 'u', 'u', 'Latin Small Letter U with grave', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00FA', 'ú', 'u', 'u', 'Latin Small Letter U with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00FB', 'û', 'u', 'u', 'Latin Small Letter U with circumflex', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00FC', 'ü', 'u', 'u', 'Latin Small Letter U with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00FD', 'ý', 'y', 'y', 'Latin Small Letter Y with acute', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00FE', 'þ', 'th', 'th', 'Latin Small Letter Thorn', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('00FF', 'ÿ', 'y', 'y', 'Latin Small Letter Y with diaeresis', 'Latin-1 Supplement', 'Latin letters', NULL, FALSE),
('0100', 'Ā', 'A', 'a', 'Latin Capital letter A with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0101', 'ā', 'a', 'a', 'Latin Small letter A with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0102', 'Ă', 'A', 'a', 'Latin Capital letter A with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0103', 'ă', 'a', 'a', 'Latin Small letter A with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0104', 'Ą', 'A', 'a', 'Latin Capital letter A with ogonek', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0105', 'ą', 'a', 'a', 'Latin Small letter A with ogonek', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0106', 'Ć', 'C', 'c', 'Latin Capital letter C with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0107', 'ć', 'c', 'c', 'Latin Small letter C with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0108', 'Ĉ', 'C', 'c', 'Latin Capital letter C with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0109', 'ĉ', 'c', 'c', 'Latin Small letter C with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('010A', 'Ċ', 'C', 'c', 'Latin Capital letter C with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('010B', 'ċ', 'c', 'c', 'Latin Small letter C with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('010C', 'Č', 'C', 'c', 'Latin Capital letter C with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('010D', 'č', 'c', 'c', 'Latin Small letter C with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('010E', 'Ď', 'D', 'd', 'Latin Capital letter D with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('010F', 'ď', 'd', 'd', 'Latin Small letter D with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0110', 'Đ', 'D', 'd', 'Latin Capital letter D with stroke', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0111', 'đ', 'd', 'd', 'Latin Small letter D with stroke', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0112', 'Ē', 'E', 'e', 'Latin Capital letter E with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0113', 'ē', 'e', 'e', 'Latin Small letter E with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0114', 'Ĕ', 'E', 'e', 'Latin Capital letter E with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0115', 'ĕ', 'e', 'e', 'Latin Small letter E with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0116', 'Ė', 'E', 'e', 'Latin Capital letter E with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0117', 'ė', 'e', 'e', 'Latin Small letter E with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0118', 'Ę', 'E', 'e', 'Latin Capital letter E with ogonek', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0119', 'ę', 'e', 'e', 'Latin Small letter E with ogonek', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('011A', 'Ě', 'E', 'e', 'Latin Capital letter E with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('011B', 'ě', 'e', 'e', 'Latin Small letter E with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('011C', 'Ĝ', 'G', 'g', 'Latin Capital letter G with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('011D', 'ĝ', 'g', 'g', 'Latin Small letter G with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('011E', 'Ğ', 'G', 'g', 'Latin Capital letter G with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('011F', 'ğ', 'g', 'g', 'Latin Small letter G with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0120', 'Ġ', 'G', 'g', 'Latin Capital letter G with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0121', 'ġ', 'g', 'g', 'Latin Small letter G with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0122', 'Ģ', 'G', 'g', 'Latin Capital letter G with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0123', 'ģ', 'g', 'g', 'Latin Small letter G with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0124', 'Ĥ', 'H', 'h', 'Latin Capital letter H with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0125', 'ĥ', 'h', 'h', 'Latin Small letter H with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0126', 'Ħ', 'H', 'h', 'Latin Capital letter H with stroke', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0127', 'ħ', 'h', 'h', 'Latin Small letter H with stroke', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0128', 'Ĩ', 'I', 'i', 'Latin Capital letter I with tilde', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0129', 'ĩ', 'i', 'i', 'Latin Small letter I with tilde', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('012A', 'Ī', 'I', 'i', 'Latin Capital letter I with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('012B', 'ī', 'i', 'i', 'Latin Small letter I with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('012C', 'Ĭ', 'I', 'i', 'Latin Capital letter I with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('012D', 'ĭ', 'i', 'i', 'Latin Small letter I with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('012E', 'Į', 'I', 'i', 'Latin Capital letter I with ogonek', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('012F', 'į', 'i', 'i', 'Latin Small letter I with ogonek', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
/* ('0130', 'İ', 'I', 'i', 'Latin Capital letter I with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE), 
--Not found in dataset, unlikely to appear, and testing this character is difficult */
('0131', 'ı', 'i', 'i', 'Latin Small letter dotless I', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0132', 'Ĳ', 'IJ', 'ij', 'Latin Capital Ligature IJ', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0133', 'ĳ', 'ij', 'ij', 'Latin Small Ligature IJ', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0134', 'Ĵ', 'J', 'j', 'Latin Capital letter J with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0135', 'ĵ', 'j', 'j', 'Latin Small letter J with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0136', 'Ķ', 'K', 'k', 'Latin Capital letter K with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0137', 'ķ', 'k', 'k', 'Latin Small letter K with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0138', 'ĸ', 'k', 'k', 'Latin Small letter Kra', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0139', 'Ĺ', 'L', 'l', 'Latin Capital letter L with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('013A', 'ĺ', 'l', 'l', 'Latin Small letter L with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('013B', 'Ļ', 'L', 'l', 'Latin Capital letter L with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('013C', 'ļ', 'l', 'l', 'Latin Small letter L with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('013D', 'Ľ', 'L', 'l', 'Latin Capital letter L with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('013E', 'ľ', 'l', 'l', 'Latin Small letter L with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('013F', 'Ŀ', 'L', 'l', 'Latin Capital letter L with middle dot', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0140', 'ŀ', 'l', 'l', 'Latin Small letter L with middle dot', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0141', 'Ł', 'L', 'l', 'Latin Capital letter L with stroke', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0142', 'ł', 'l', 'l', 'Latin Small letter L with stroke', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0143', 'Ń', 'N', 'n', 'Latin Capital letter N with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0144', 'ń', 'n', 'n', 'Latin Small letter N with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0145', 'Ņ', 'N', 'n', 'Latin Capital letter N with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0146', 'ņ', 'n', 'n', 'Latin Small letter N with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0147', 'Ň', 'N', 'n', 'Latin Capital letter N with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0148', 'ň', 'n', 'n', 'Latin Small letter N with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
/* Character \u0149 is deprecated, and unlikely to appear in our datasets. */
('014A', 'Ŋ', 'ng', 'ng', 'Latin Capital letter Eng', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('014B', 'ŋ', 'NG', 'ng', 'Latin Small letter Eng', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('014C', 'Ō', 'O', 'o', 'Latin Capital letter O with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('014D', 'ō', 'o', 'o', 'Latin Small letter O with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('014E', 'Ŏ', 'O', 'o', 'Latin Capital letter O with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('014F', 'ŏ', 'o', 'o', 'Latin Small letter O with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0150', 'Ő', 'O', 'o', 'Latin Capital Letter O with double acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0151', 'ő', 'o', 'o', 'Latin Small Letter O with double acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0152', 'Œ', 'OE', 'oe', 'Latin Capital Ligature OE', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0153', 'œ', 'oe', 'oe', 'Latin Small Ligature OE', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0154', 'Ŕ', 'R', 'r', 'Latin Capital letter R with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0155', 'ŕ', 'r', 'r', 'Latin Small letter R with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0156', 'Ŗ', 'R', 'r', 'Latin Capital letter R with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0157', 'ŗ', 'r', 'r', 'Latin Small letter R with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0158', 'Ř', 'R', 'r', 'Latin Capital letter R with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0159', 'ř', 'r', 'r', 'Latin Small letter R with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('015A', 'Ś', 'S', 's', 'Latin Capital letter S with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('015B', 'ś', 's', 's', 'Latin Small letter S with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('015C', 'Ŝ', 'S', 's', 'Latin Capital letter S with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('015D', 'ŝ', 's', 's', 'Latin Small letter S with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('015E', 'Ş', 'S', 's', 'Latin Capital letter S with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('015F', 'ş', 's', 's', 'Latin Small letter S with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0160', 'Š', 'S', 's', 'Latin Capital letter S with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0161', 'š', 's', 's', 'Latin Small letter S with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0162', 'Ţ', 'T', 't', 'Latin Capital letter T with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0163', 'ţ', 't', 't', 'Latin Small letter T with cedilla', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0164', 'Ť', 'T', 't', 'Latin Capital letter T with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0165', 'ť', 't', 't', 'Latin Small letter T with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0166', 'Ŧ', 'T', 't', 'Latin Capital letter T with stroke', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0167', 'ŧ', 't', 't', 'Latin Small letter T with stroke', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0168', 'Ũ', 'U', 'u', 'Latin Capital letter U with tilde', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0169', 'ũ', 'u', 'u', 'Latin Small letter U with tilde', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('016A', 'Ū', 'U', 'u', 'Latin Capital letter U with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('016B', 'ū', 'u', 'u', 'Latin Small letter U with macron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('016C', 'Ŭ', 'U', 'u', 'Latin Capital letter U with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('016D', 'ŭ', 'u', 'u', 'Latin Small letter U with breve', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('016E', 'Ů', 'U', 'u', 'Latin Capital letter U with ring above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('016F', 'ů', 'u', 'u', 'Latin Small letter U with ring above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0170', 'Ű', 'U', 'u', 'Latin Capital Letter U with double acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0171', 'ű', 'u', 'u', 'Latin Small Letter U with double acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0172', 'Ų', 'U', 'u', 'Latin Capital letter U with ogonek', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0173', 'ų', 'u', 'u', 'Latin Small letter U with ogonek', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0174', 'Ŵ', 'W', 'w', 'Latin Capital letter W with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0175', 'ŵ', 'w', 'w', 'Latin Small letter W with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0176', 'Ŷ', 'Y', 'y', 'Latin Capital letter Y with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0177', 'ŷ', 'y', 'y', 'Latin Small letter Y with circumflex', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0178', 'Ÿ', 'Y', 'y', 'Latin Capital letter Y with diaeresis', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0179', 'Ź', 'Z', 'z', 'Latin Capital letter Z with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('017A', 'ź', 'z', 'z', 'Latin Small letter Z with acute', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('017B', 'Ż', 'Z', 'z', 'Latin Capital letter Z with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('017C', 'ż', 'z', 'z', 'Latin Small letter Z with dot above', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('017D', 'Ž', 'Z', 'z', 'Latin Capital letter Z with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('017E', 'ž', 'z', 'z', 'Latin Small letter Z with caron', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('017F', 'ſ', 's', 's', 'Latin Small letter long S', 'Latin Extended-A', 'Latin letters', NULL, FALSE),
('0180', 'ƀ', 'b', 'b', 'Latin Small Letter B with Stroke', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0181', 'Ɓ', 'B', 'b', 'Latin Capital Letter B with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0182', 'Ƃ', 'B', 'b', 'Latin Capital Letter B with Top Bar', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0183', 'ƃ', 'b', 'b', 'Latin Small Letter B with Top Bar', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0184', 'Ƅ', '6', '6', 'Latin Capital Letter Tone Six', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0185', 'ƅ', '6', '6', 'Latin Small Letter Tone Six', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0186', 'Ɔ', 'O', 'o', 'Latin Capital Letter Open O', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0187', 'Ƈ', 'C', 'c', 'Latin Capital Letter C with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0188', 'ƈ', 'c', 'c', 'Latin Small Letter C with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0189', 'Ɖ', 'D', 'd', 'Latin Capital Letter African D', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('018A', 'Ɗ', 'D', 'd', 'Latin Capital Letter D with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('018B', 'Ƌ', 'D', 'd', 'Latin Capital Letter D with Top Bar', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('018C', 'ƌ', 'd', 'd', 'Latin Small Letter D with Top Bar', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('018D', 'ƍ', 'd', 'd', 'Latin Small Letter Turned Delta', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('018E', 'Ǝ', '3', '3', 'Latin Capital Letter Reversed E', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
/* ('018F', 'Ə', '@', '', 'Latin Capital Letter Schwa', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE), 
--Not found in dataset, unlikely to appear, and testing this character is difficult */
('0190', 'Ɛ', 'E', 'e', 'Latin Capital Letter Open E', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0191', 'Ƒ', 'F', 'f', 'Latin Capital Letter F with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0192', 'ƒ', 'f', 'f', 'Latin Small Letter F with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0193', 'Ɠ', 'G', 'g', 'Latin Capital Letter G with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0194', 'Ɣ', 'G', 'g', 'Latin Capital Letter Gamma', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0195', 'ƕ', 'hv', 'hv', 'Latin Small Letter HV', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0196', 'Ɩ', 'I', 'i', 'Latin Capital Letter Iota', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0197', 'Ɨ', 'I', 'i', 'Latin Capital Letter I with Stroke', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0198', 'Ƙ', 'K', 'k', 'Latin Capital Letter K with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('0199', 'ƙ', 'k', 'k', 'Latin Small Letter K with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('019A', 'ƚ', 'l', 'l', 'Latin Small Letter L with Bar', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('019B', 'ƛ', 'l', 'l', 'Latin Small Letter Lambda with Stroke', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('019C', 'Ɯ', 'W', 'w', 'Latin Capital Letter Turned M', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('019D', 'Ɲ', 'N', 'n', 'Latin Capital Letter N with Left Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('019E', 'ƞ', 'n', 'n', 'Latin Small Letter N with Long Right Leg', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('019F', 'Ɵ', 'O', 'o', 'Latin Capital Letter O with Middle Tilde', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A0', 'Ơ', 'O', 'o', 'Latin Capital Letter O with Horn', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A1', 'ơ', 'o', 'o', 'Latin Small Letter O with Horn', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A2', 'Ƣ', 'OI', 'oi', 'Latin Capital Letter OI (= Latin Capital Letter Gha)', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A3', 'ƣ', 'oi', 'oi', 'Latin Small Letter OI (= Latin Small Letter Gha)', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A4', 'Ƥ', 'P', 'p', 'Latin Capital Letter P with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A5', 'ƥ', 'p', 'p', 'Latin Small Letter P with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A6', 'Ʀ', 'YR', 'yr', 'Latin Letter YR', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A7', 'Ƨ', '2', '2', 'Latin Capital Letter Tone Two', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A8', 'ƨ', '2', '2', 'Latin Small Letter Tone Two', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01A9', 'Ʃ', 'SH', 'sh', 'Latin Capital Letter Esh', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01AA', 'ƪ', 'sh', 'sh', 'Latin Letter Reversed Esh Loop', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01AB', 'ƫ', 't', 't', 'Latin Small Letter T with Palatal Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01AC', 'Ƭ', 'T', 't', 'Latin Capital Letter T with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01AD', 'ƭ', 't', 't', 'Latin Small Letter T with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01AE', 'Ʈ', 'T', 't', 'Latin Capital Letter T with Retroflex Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01AF', 'Ư', 'U', 'u', 'Latin Capital Letter U with Horn', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B0', 'ư', 'u', 'u', 'Latin Small Letter U with Horn', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B1', 'Ʊ', 'Y', 'y', 'Latin Capital Letter Upsilon', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B2', 'Ʋ', 'V', 'v', 'Latin Capital Letter V with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B3', 'Ƴ', 'Y', 'y', 'Latin Capital Letter Y with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B4', 'ƴ', 'y', 'y', 'Latin Small Letter Y with Hook', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B5', 'Ƶ', 'Z', 'z', 'Latin Capital Letter Z with Stroke', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B6', 'ƶ', 'z', 'z', 'Latin Small Letter Z with Stroke', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B7', 'Ʒ', 'ZH', 'zh', 'Latin Capital Letter Ezh', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B8', 'Ƹ', 'ZH', 'zh', 'Latin Capital Letter Ezh Reversed', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01B9', 'ƹ', 'zh', 'zh', 'Latin Small Letter Ezh Reversed', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01BA', 'ƺ', 'zh', 'zh', 'Latin Small Letter Ezh with Tail', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01BB', 'ƻ', '2', '2', 'Latin Letter Two with Stroke', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01BC', 'Ƽ', '5', '5', 'Latin Capital Letter Tone Five', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01BD', 'ƽ', '5', '5', 'Latin Small Letter Tone Five', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01BE', 'ƾ', 'ts', 'ts', 'Latin Letter Inverted Glottal Stop with Stroke', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01BF', 'ƿ', 'w', 'w', 'Latin Letter Wynn', 'Latin Extended-B', 'Non-European Latin letters', NULL, FALSE),
('01C0', 'ǀ', '|', '', 'Latin Letter Dental Click', 'Latin Extended-B', 'African', NULL, FALSE),
('01C1', 'ǁ', '||', '', 'Latin Letter Lateral Click', 'Latin Extended-B', 'African', NULL, FALSE),
('01C2', 'ǂ', '|=', '', 'Latin Letter Alveolar Click', 'Latin Extended-B', 'African', NULL, FALSE),
('01C3', 'ǃ', '!', '', 'Latin Letter Retroflex Click', 'Latin Extended-B', 'African', NULL, FALSE),
('01C4', 'Ǆ', 'DZ', 'dz', 'Latin Capital Letter DZ with Caron', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01C5', 'ǅ', 'Dz', 'dz', 'Latin Capital Letter D with Small Letter Z with Caron', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01C6', 'ǆ', 'dz', 'dz', 'Latin Small Letter DZ with Caron', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01C7', 'Ǉ', 'LJ', 'lj', 'Latin Capital Letter LJ', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01C8', 'ǈ', 'Lj', 'lj', 'Latin Capital Letter L with Small Letter J', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01C9', 'ǉ', 'lj', 'lj', 'Latin Small Letter LJ', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01CA', 'Ǌ', 'NJ', 'nj', 'Latin Capital Letter NJ', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01CB', 'ǋ', 'Nj', 'nj', 'Latin Capital Letter N with Small Letter J', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01CC', 'ǌ', 'nj', 'nj', 'Latin Small Letter NJ', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('01CD', 'Ǎ', 'A', 'a', 'Latin Capital Letter A with Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01CE', 'ǎ', 'a', 'a', 'Latin Small Letter A with Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01CF', 'Ǐ', 'I', 'i', 'Latin Capital Letter I with Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D0', 'ǐ', 'i', 'i', 'Latin Small Letter I with Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D1', 'Ǒ', 'O', 'o', 'Latin Capital Letter O with Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D2', 'ǒ', 'o', 'o', 'Latin Small Letter O with Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D3', 'Ǔ', 'U', 'u', 'Latin Capital Letter U with Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D4', 'ǔ', 'u', 'u', 'Latin Small Letter U with Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D5', 'Ǖ', 'U', 'u', 'Latin Capital Letter U with Diaeresis and Macron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D6', 'ǖ', 'u', 'u', 'Latin Small Letter U with Diaeresis and Macron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D7', 'Ǘ', 'U', 'u', 'Latin Capital Letter U with Diaeresis and Acute', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D8', 'ǘ', 'u', 'u', 'Latin Small Letter U with Diaeresis and Acute', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01D9', 'Ǚ', 'U', 'u', 'Latin Capital Letter U with Diaeresis and Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01DA', 'ǚ', 'u', 'u', 'Latin Small Letter U with Diaeresis and Caron', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01DB', 'Ǜ', 'U', 'u', 'Latin Capital Letter U with Diaeresis and Grave', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
('01DC', 'ǜ', 'u', 'u', 'Latin Small Letter U with Diaeresis and Grave', 'Latin Extended-B', 'Pinyin', NULL, FALSE),
/* ('01DD', 'ǝ', '@', '', 'Latin Small Letter Turned E', 'Latin Extended-B', 'Phonetic', NULL, FALSE), 
--Not found in dataset, unlikely to appear, and testing this character is difficult */
('01DE', 'Ǟ', 'A', 'a', 'Latin Capital Letter A with Diaeresis and Macron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01DF', 'ǟ', 'a', 'a', 'Latin Small Letter A with Diaeresis and Macron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E0', 'Ǡ', 'A', 'a', 'Latin Capital Letter A with Dot Above and Macron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E1', 'ǡ', 'a', 'a', 'Latin Small Letter A with Dot Above and Macron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E2', 'Ǣ', 'AE', 'ae', 'Latin Capital Letter AE with Macron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E3', 'ǣ', 'ae', 'ae', 'Latin Small Letter AE with Macron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E4', 'Ǥ', 'G', 'g', 'Latin Capital Letter G with Stroke', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E5', 'ǥ', 'g', 'g', 'Latin Small Letter G with Stroke', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E6', 'Ǧ', 'G', 'g', 'Latin Capital Letter G with Caron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E7', 'ǧ', 'g', 'g', 'Latin Small Letter G with Caron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E8', 'Ǩ', 'K', 'k', 'Latin Capital Letter K with Caron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01E9', 'ǩ', 'k', 'k', 'Latin Small Letter K with Caron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01EA', 'Ǫ', 'O', 'o', 'Latin Capital Letter O with Ogonek', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01EB', 'ǫ', 'o', 'o', 'Latin Small Letter O with Ogonek', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01EC', 'Ǭ', 'O', 'o', 'Latin Capital Letter O with Ogonek and Macron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01ED', 'ǭ', 'o', 'o', 'Latin Small Letter O with Ogonek and Macron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01EE', 'Ǯ', 'ZH', 'zh', 'Latin Capital Letter Ezh with Caron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01EF', 'ǯ', 'zh', 'zh', 'Latin Small Letter Ezh with Caron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F0', 'ǰ', 'j', 'j', 'Latin Small Letter J with Caron', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F1', 'Ǳ', 'DZ', 'dz', 'Latin Capital Letter DZ', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F2', 'ǲ', 'Dz', 'dz', 'Latin Capital Letter D with Small Letter Z', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F3', 'ǳ', 'dz', 'dz', 'Latin Small Letter DZ', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F4', 'Ǵ', 'G', 'g', 'Latin Capital Letter G with Acute', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F5', 'ǵ', 'g', 'g', 'Latin Small Letter G with Acute', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F6', 'Ƕ', 'HV', 'hv', 'Latin Capital Letter Hwair', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F7', 'Ƿ', 'W', 'w', 'Latin Capital Letter Wynn', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F8', 'Ǹ', 'N', 'n', 'Latin Capital Letter N with Grave', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01F9', 'ǹ', 'n', 'n', 'Latin Small Letter N with Grave', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01FA', 'Ǻ', 'A', 'a', 'Latin Capital Letter A with Ring Above and Acute', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01FB', 'ǻ', 'a', 'a', 'Latin Small Letter A with Ring Above and Acute', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01FC', 'Ǽ', 'AE', 'ae', 'Latin Capital Letter AE with Acute', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01FD', 'ǽ', 'ae', 'ae', 'Latin Small Letter AE with Acute', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01FE', 'Ǿ', 'O', 'o', 'Latin Capital Letter O with Stroke and Acute', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('01FF', 'ǿ', 'o', 'o', 'Latin Small Letter O with Stroke and Acute', 'Latin Extended-B', 'Phonetic', NULL, FALSE),
('0200', 'Ȁ', 'A', 'a', 'Latin Capital Letter A with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0201', 'ȁ', 'a', 'a', 'Latin Small Letter A with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0202', 'Ȃ', 'A', 'a', 'Latin Capital Letter A with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0203', 'ȃ', 'a', 'a', 'Latin Small Letter A with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0204', 'Ȅ', 'E', 'e', 'Latin Capital Letter E with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0205', 'ȅ', 'e', 'e', 'Latin Small Letter E with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0206', 'Ȇ', 'E', 'e', 'Latin Capital Letter E with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0207', 'ȇ', 'e', 'e', 'Latin Small Letter E with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0208', 'Ȉ', 'I', 'i', 'Latin Capital Letter I with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0209', 'ȉ', 'i', 'i', 'Latin Small Letter I with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('020A', 'Ȋ', 'I', 'i', 'Latin Capital Letter I with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('020B', 'ȋ', 'i', 'i', 'Latin Small Letter I with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('020C', 'Ȍ', 'O', 'o', 'Latin Capital Letter O with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('020D', 'ȍ', 'o', 'o', 'Latin Small Letter O with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('020E', 'Ȏ', 'O', 'o', 'Latin Capital Letter O with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('020F', 'ȏ', 'o', 'o', 'Latin Small Letter O with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0210', 'Ȑ', 'R', 'r', 'Latin Capital Letter R with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0211', 'ȑ', 'r', 'r', 'Latin Small Letter R with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0212', 'Ȓ', 'R', 'r', 'Latin Capital Letter R with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0213', 'ȓ', 'r', 'r', 'Latin Small Letter R with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0214', 'Ȕ', 'U', 'u', 'Latin Capital Letter U with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0215', 'ȕ', 'u', 'u', 'Latin Small Letter U with Double Grave', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0216', 'Ȗ', 'U', 'u', 'Latin Capital Letter U with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0217', 'ȗ', 'u', 'u', 'Latin Small Letter U with Inverted Breve', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0218', 'Ș', 'S', 's', 'Latin Capital Letter S with Comma Below', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('0219', 'ș', 's', 's', 'Latin Small Letter S with Comma Below', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('021A', 'Ț', 'T', 't', 'Latin Capital Letter T with Comma Below', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('021B', 'ț', 't', 't', 'Latin Small Letter T with Comma Below', 'Latin Extended-B', 'Latin letters', NULL, FALSE),
('021C', 'Ȝ', 'Y', 'y', 'Latin Capital Letter Yogh', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('021D', 'ȝ', 'y', 'y', 'Latin Small Letter Yogh', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('021E', 'Ȟ', 'H', 'h', 'Latin Capital Letter H with Caron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('021F', 'ȟ', 'h', 'h', 'Latin Small Letter H with Caron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0220', 'Ƞ', 'N', 'n', 'Latin Capital Letter N with Long Right Leg', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0221', 'ȡ', 'd', 'd', 'Latin Small Letter D with Curl', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0222', 'Ȣ', 'OU', 'ou', 'Latin Capital Letter OU', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0223', 'ȣ', 'ou', 'ou', 'Latin Small Letter OU', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0224', 'Ȥ', 'Z', 'z', 'Latin Capital Letter Z with Hook', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0225', 'ȥ', 'z', 'z', 'Latin Small Letter Z with Hook', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0226', 'Ȧ', 'A', 'a', 'Latin Capital Letter A with Dot Above', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0227', 'ȧ', 'a', 'a', 'Latin Small Letter A with Dot Above', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0228', 'Ȩ', 'E', 'e', 'Latin Capital Letter E with Cedilla', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0229', 'ȩ', 'e', 'e', 'Latin Small Letter E with Cedilla', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('022A', 'Ȫ', 'O', 'o', 'Latin Capital Letter O with Diaeresis and Macron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('022B', 'ȫ', 'o', 'o', 'Latin Small Letter O with Diaeresis and Macron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('022C', 'Ȭ', 'O', 'o', 'Latin Capital Letter O with Tilde and Macron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('022D', 'ȭ', 'o', 'o', 'Latin Small Letter O with Tilde and Macron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('022E', 'Ȯ', 'O', 'o', 'Latin Capital Letter O with Dot Above', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('022F', 'ȯ', 'o', 'o', 'Latin Small Letter O with Dot Above', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0230', 'Ȱ', 'O', 'o', 'Latin Capital Letter O with Dot Above and Macron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0231', 'ȱ', 'o', 'o', 'Latin Small Letter O with Dot Above and Macron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0232', 'Ȳ', 'Y', 'y', 'Latin Capital Letter Y with Macron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0233', 'ȳ', 'y', 'y', 'Latin Small Letter Y with Macron', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0234', 'ȴ', 'l', 'l', 'Latin Small Letter L with Curl', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0235', 'ȵ', 'n', 'n', 'Latin Small Letter N with Curl', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0236', 'ȶ', 't', 't', 'Latin Small Letter T with Curl', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0237', 'ȷ', 'j', 'j', 'Latin Small Letter Dotless J', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0238', 'ȸ', 'db', 'db', 'Latin Small Letter DB Digraph', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0239', 'ȹ', 'qp', 'qp', 'Latin Small Letter QP Digraph', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('023A', 'Ⱥ', 'A', 'a', 'Latin Capital Letter A with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('023B', 'Ȼ', 'C', 'c', 'Latin Capital Letter C with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('023C', 'ȼ', 'c', 'c', 'Latin Small Letter C with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('023D', 'Ƚ', 'L', 'l', 'Latin Capital Letter L with Bar', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('023E', 'Ⱦ', 'T', 't', 'Latin Capital Letter T with Diagonal Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('023F', 'ȿ', 's', 's', 'Latin Small Letter S with Swash Tail', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0240', 'ɀ', 'z', 'z', 'Latin Small Letter Z with Swash Tail', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0241', 'Ɂ', '', '', 'Latin Capital Letter Glottal Stop', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0242', 'ɂ', '', '', 'Latin Small Letter Glottal Stop', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0243', 'Ƀ', 'B', 'b', 'Latin Capital Letter B with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0244', 'Ʉ', 'U', 'u', 'Latin Capital Letter U Bar', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
/* ('0245', 'Ʌ', '^', '', 'Latin Capital Letter Turned V', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE), 
--Not found in dataset, unlikely to appear, and testing this character is difficult */
('0246', 'Ɇ', 'E', 'e', 'Latin Capital Letter E with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0247', 'ɇ', 'e', 'e', 'Latin Small Letter E with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0248', 'Ɉ', 'J', 'j', 'Latin Capital Letter J with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('0249', 'ɉ', 'j', 'j', 'Latin Small Letter J with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('024A', 'Ɋ', 'q', 'q', 'Latin Capital Letter Q with Hook Tail', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('024B', 'ɋ', 'q', 'q', 'Latin Small Letter Q with Hook Tail', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('024C', 'Ɍ', 'R', 'r', 'Latin Capital Letter R with stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('024D', 'ɍ', 'r', 'r', 'Latin Small Letter R with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('024E', 'Ɏ', 'Y', 'y', 'Latin Capital Letter Y with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('024F', 'ɏ', 'y', 'y', 'Latin Small Letter Y with Stroke', 'Latin Extended-B', 'Miscellaneous', NULL, FALSE),
('2013', '–', '-', '', 'En Dash', 'General Punctuation', 'Punctuation', NULL, FALSE),
('2014', '—', '-', '', 'Em Dash', 'General Punctuation', 'Punctuation', NULL, FALSE),
('2018', '‘', '''', '', 'Left Single Quotation Mark', 'General Punctuation', 'Punctuation', NULL, FALSE),
('2019', '’', '''', '', 'Right Single Quotation Mark', 'General Punctuation', 'Punctuation', NULL, FALSE),
('201A', '‚', ',', '', 'Single Low-9 Quotation Mark', 'General Punctuation', 'Punctuation', NULL, FALSE),
('201C', '“', '"', '', 'Left Double Quotation Mark', 'General Punctuation', 'Punctuation', NULL, FALSE),
('201D', '”', '"', '', 'Right Double Quotation Mark', 'General Punctuation', 'Punctuation', NULL, FALSE),
('201E', '„', ',,', '', 'Double Low-9 Quotation Mark', 'General Punctuation', 'Punctuation', NULL, FALSE),
('2026', '…', '...', '', 'Horizontal Ellipsis', 'General Punctuation', 'Punctuation', NULL, FALSE),
('20AC', '€', 'EUR', '', 'Euro Sign', 'Currency Symbols', 'Punctuation', NULL, FALSE)
