/* this file will create a table defining substituations for simplifying */
/* company names in preparation for fuzzy matching */ 

CREATE TABLE etl.company_name_replacements (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_replace TEXT NOT NULL UNIQUE,
  replacement TEXT NOT NULL,
  regexp_flags TEXT NOT NULL DEFAULT 'g'
);
CREATE INDEX ix_unicode_point_codepoint ON etl.unicode_point (codepoint);

INSERT INTO etl.company_name_replacements (
  to_replace, replacement, regexp_flags
) VALUES
('development', 'dev', 'g'),
('develop', 'dev', 'g')
