/* this file will create a table defining substituations for simplifying */
/* company names in preparation for fuzzy matching */ 

CREATE TABLE etl.company_name_abbreviations (
  to_replace TEXT NOT NULL UNIQUE,
  replacement TEXT NOT NULL,
  regexp_flags TEXT NOT NULL DEFAULT 'ig'
);
CREATE INDEX ix_company_name_replacement_cover ON etl.company_name_abbreviations (
  to_replace,
  replacement,
  regexp_flags
);

INSERT INTO etl.company_name_abbreviations (
  to_replace, replacement, regexp_flags
) VALUES
('(inactive)', '', 'ig'),
(' and ', ' & ', 'ig'),
(' och ', ' & ', 'ig'),
(' en ', ' & ', 'ig'),
(' und ', ' & ', 'ig'),
('development', 'dev', 'ig'),
('develop', 'dev', 'ig'),
('group', 'grp', 'ig'),
('designated activity company', 'dac', 'ig'),
('limited partnership', 'lp', 'ig'),
('generation', 'gen', 'ig'),
('investment', 'invest', 'ig'),
('limited', 'ltd', 'ig'),
('company', 'co', 'ig'),
('public ltd co', 'plc', 'ig'),
('corporation', 'corp', 'ig'),
('ltd liability co', 'llc', 'ig'),
('aktg', 'ag', 'ig'),
('aktiengesellschaft', 'ag', 'ig'),
('incorporated', 'inc', 'ig'),
('holdings', 'hldgs', 'ig'),
('holding', 'hldgs', 'ig'),
('international', 'intl', 'ig'),
('government', 'govt', 'ig'),
('berhad', 'bhd', 'ig'),
('resources', 'res', 'ig'),
('resource', 'res', 'ig'),
('shipping', 'shp', 'ig'),
('partners', 'prt', 'ig'),
('partner', 'prt', 'ig'),
('associates', 'assoc', 'ig'),
('associate', 'assoc', 'ig'),
(' dac$', '$dac', 'i'),
(' sas$', '$sas', 'i'),
(' asa$', '$asa', 'i'),
(' spa$', '$spa', 'i'),
(' pte$', '$pte', 'i'),
(' srl$', '$srl', 'i'),
(' ltd$', '$ltd', 'i'),
(' plc$', '$plc', 'i'),
(' pcl$', '$pcl', 'i'),
(' bsc$', '$bsc', 'i'),
(' sarl$', '$sarl', 'i'),
(' as$', '$as', 'i'),
(' nv$', '$nv', 'i'),
(' bv$', '$bv', 'i'),
(' cv$', '$cv', 'i'),
(' pt$', '$pt', 'i'),
(' sa$', '$sa', 'i'),
(' se$', '$se', 'i'),
(' lp$', '$lp', 'i'),
(' corp$', '$corp', 'i'),
(' co$', '$co', 'i'),
(' llc$', '$llc', 'i'),
(' ag$', '$ag', 'i'),
(' inc$', '$inc', 'i'),
(' hldgs$', '$hldgs', 'i'),
(' intl$', '$intl', 'i'),
(' govt$', '$govt', 'i'),
(' bhd$', '$bhd', 'i'),
(' lt$', '$ltd', 'i'),
('financial', 'fin', 'ig')
;
